dist: xenial
language: python
python:
  - "3.7"
# command to install dependencies
env:
  - DOCKER_FILE=docker/docker-compose-dev.yml
services:
  - docker
install:
  - pip install -r requirements.dev.txt
before_script:
# Let's stop postgresql
  - sudo service postgresql stop
# wait for postgresql to shutdown.
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose -f $DOCKER_FILE up --build --no-start
  - docker-compose -f $DOCKER_FILE start
# blocklist
branches:
  except:
  - /wip*/
script:
  - docker-compose -f $DOCKER_FILE run backend pytest ./backend/
