version: '3.7'

services:
  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - REQUIREMENTS=/tmp/requirements/requirements.dev.txt
    command: bash ../docker/run.sh -d
    depends_on:
      - "db"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
  db:
    image: postgres
    ports:
    - 5433:5432
